package view;

import controller.Controller;
import static controller.Controller.Delete;
import static controller.Controller.BotaoEditar;
import static controller.Controller.Tela2;
import static controller.Controller.Tela3;
import static controller.Controller.pesquisarContato;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Livro;

/**
 *
 * @author Eliaquim, João, Laryssa, Sérgio
 */
public class TelaInicio extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicio() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        
        listarJTable();
        
    }
    
    public void listarJTable(){
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.setNumRows(0);
        Controller c = new Controller();
        
        for(Livro l: c.Listar()){
            
            modelo.addRow(new Object[]{
                l.getCodigo(),
                l.getNomeLivro(),
                l.getGenero(),
                l.getNomeAutor(),
                l.getEditora()
            });
                    
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelBranco = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButtonTelaApagar = new javax.swing.JButton();
        jButtonTelaEditar = new javax.swing.JButton();
        jButtonTelaNovo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextFieldPesquisa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Inicial");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelAzul.setBackground(new java.awt.Color(52, 73, 94));
        jPanelAzul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(jLabel1.getFont().deriveFont((float)48));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Livros");
        jPanelAzul.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 21, -1, -1));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-read-48 (1).png"))); // NOI18N
        jPanelAzul.add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 30, -1, -1));

        getContentPane().add(jPanelAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        jPanelBranco.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBranco.setMinimumSize(new java.awt.Dimension(734, 397));
        jPanelBranco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Gênero", "Autor", "Editora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setGridColor(new java.awt.Color(255, 255, 255));
        tabela.setIntercellSpacing(new java.awt.Dimension(5, 5));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        tabela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(0).setPreferredWidth(1);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabela.getColumnModel().getColumn(2).setResizable(false);
            tabela.getColumnModel().getColumn(3).setResizable(false);
            tabela.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanelBranco.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 84, 668, 235));

        jButtonTelaApagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTelaApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-delete-file-48 (1).png"))); // NOI18N
        jButtonTelaApagar.setText("Apagar");
        jButtonTelaApagar.setContentAreaFilled(false);
        jButtonTelaApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaApagarActionPerformed(evt);
            }
        });
        jPanelBranco.add(jButtonTelaApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 337, 150, 60));

        jButtonTelaEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTelaEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-file-48 (1).png"))); // NOI18N
        jButtonTelaEditar.setText("Editar");
        jButtonTelaEditar.setContentAreaFilled(false);
        jButtonTelaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaEditarActionPerformed(evt);
            }
        });
        jPanelBranco.add(jButtonTelaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 337, 140, 60));

        jButtonTelaNovo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTelaNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-read-48 (2).png"))); // NOI18N
        jButtonTelaNovo.setText("Adicionar");
        jButtonTelaNovo.setContentAreaFilled(false);
        jButtonTelaNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaNovoActionPerformed(evt);
            }
        });
        jPanelBranco.add(jButtonTelaNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 337, 250, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-search-30.png"))); // NOI18N
        jPanelBranco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 36, -1, -1));

        jFormattedTextFieldPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextFieldPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldPesquisaKeyReleased(evt);
            }
        });
        jPanelBranco.add(jFormattedTextFieldPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 36, 296, 30));

        getContentPane().add(jPanelBranco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTelaNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaNovoActionPerformed
        Tela2(this);
    }//GEN-LAST:event_jButtonTelaNovoActionPerformed

    private void jButtonTelaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaEditarActionPerformed
        BotaoEditar(tabela, this);
    }//GEN-LAST:event_jButtonTelaEditarActionPerformed

    private void jButtonTelaApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaApagarActionPerformed
        Controller.BotaoDelete(jButtonTelaNovo, tabela);
        Livro l = new Livro();
        Delete(l);
        listarJTable();
    }//GEN-LAST:event_jButtonTelaApagarActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //TabelaEditar(tabela);
    }//GEN-LAST:event_tabelaMouseClicked

    private void jFormattedTextFieldPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldPesquisaKeyReleased
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        pesquisarContato(tabela, jFormattedTextFieldPesquisa, modelo);
    }//GEN-LAST:event_jFormattedTextFieldPesquisaKeyReleased

    private void tabelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonTelaApagar;
    private javax.swing.JButton jButtonTelaEditar;
    private javax.swing.JButton jButtonTelaNovo;
    private javax.swing.JFormattedTextField jFormattedTextFieldPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanelAzul;
    private javax.swing.JPanel jPanelBranco;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
